# vim: ts=2 sw=2 et ft=yaml.ansible
---
# This adds postfix.mailq. We already have mit.mailq and we second it just to
# have a default trigger (for hosts which use mails for logcheck etc.) and a
# trigger with a higher severity for postfix email servers
- name: Add zabbix-agent configuration file
  ansible.builtin.copy:
    src: local-userparameter_postfix.conf
    dest: '{{ zabbix_agent_conf_dir }}'
    mode: '0644'
  notify: Restart zabbix-agent

- name: Ensure required dependencies
  ansible.builtin.apt:
    pkg: ['logtail', 'pflogsumm']

- name: Ensure zabbix_sender is installed
  ansible.builtin.command: test -f /usr/bin/zabbix_sender
  changed_when: false

- name: Add user zabbix
  ansible.builtin.user:
    name: zabbix
    groups: adm
    home: /var/lib/zabbix
    shell: /bin/false
    system: true

- name: Ensure mail alias zabbix -> root
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    line: 'zabbix: root'
    regexp: '^zabbix'

- name: Copy /usr/local/bin/zabbix-postfix.sh
  ansible.builtin.copy:
    src: zabbix-postfix.sh
    dest: /usr/local/bin/
    mode: '0755'

- name: Copy /etc/cron.d/local-zabbix-postfix
  ansible.builtin.copy:
    src: local-zabbix-postfix
    dest: /etc/cron.d/
    mode: '0644'

- name: Remove obsolete user
  ansible.builtin.user:
    name: zabbix-postfix
    state: absent

- name: Remove obsolete files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /usr/local/sbin/zabbix-postfix.sh
    - /var/lib/zabbix-postfix
